[project]
name = "plasma-improve"
authors = ["Plasma Improve Team"]
description = "A blockchain-powered meditation tracking and achievement platform"
telemetry = false
requirements = []
[contracts.meditation-tracker]
path = "contracts/meditation-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
